name: Web automated testing with Robot Framework and GitHub Actions
run-name: Pipeline Robot Framework
on: [push]
jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v2.2.2

      - name: Install packages in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  tests:
    steps:
      - name: Run test
        run: robot -d logs tests/

  artifacts:
    steps:
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            /home/runner/work/robot-github-actions/robot-github-actions/logs/output.xml
            /home/runner/work/robot-github-actions/robot-github-actions/logs/log.html
            /home/runner/work/robot-github-actions/robot-github-actions/logs/report.html