name: Web automated testing with Robot Framework and GitHub Actions
run-name: Pipeline Robot Framework
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome, Firefox and Git on OS
      uses: shreyash-Pandey-Katni/Chrome-Firefox-git-install-action@v2
      with:
        chrome: true
        firefox: true
        git: false

      - name: Install packages in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: robot -d logs tests/