name: Web automated testing with Robot Framework and GitHub Actions
run-name: Pipeline Robot Framework
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_reports_dir: 'logs'

    - name: Run test
      run: robot -d logs tests/

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          /logs/output.xml
          /logs/robotframework/reports/log.html
          /logs/robotframework/reports/report.html